version: '3'

services:
  mona:
    container_name: mongo-box
    image: mongo:3.4.8
    command: mongod --port 27017 --dbpath /data/db
    expose:
      - "27017"
    volumes:
      - mongodir:/data/db
    networks:
      - backend

  sech:
    container_name: search-box
    image: teilon/koleso:sech2
    volumes:
      - searchdir:/tmp/data
    networks:
      - backend
    depends_on:
      - mona    
    deploy:
      restart_policy:
        condition: on-failure

  send:
    container_name: sender-box
    image: teilon/koleso:send
    networks:
      - backend
    depends_on:
      - mona
    deploy:
      restart_policy:
        condition: on-failure

networks:
  backend:

volumes:
  mongodir:
  searchdir: